language: php

sudo: false

cache:
    - $HOME/.composer/cache/files

os:
  - linux

php:
    - 5.6

before_install:
    - 'echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
    - 'echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'

install:
    - travis_retry composer install --no-interaction --prefer-dist

before_script:
    - mkdir -p build/coverage
    - mkdir -p build/logs

script:
    - phpunit --coverage-clover ./build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

after_success:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

notifications:
  email:
    -  guillaume.caouissin@gmail.com
