language: php

sudo: false

cache:
    - $HOME/.composer/cache/files

os:
  - linux

php:
    - 7.0
    - 7.1
    - 7.2

install:
    - travis_retry composer install --no-interaction --prefer-dist

before_script:
    - mkdir -p build/coverage
    - mkdir -p build/logs

script:
    - phpunit --coverage-clover ./build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/php-coveralls -v

notifications:
  email:
    -  guillaume.caouissin@gmail.com
